[build]
  command = "npm run build"
  publish = "dist"

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Set security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://apis.google.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https://*.s3.amazonaws.com https://images.unsplash.com https://picsum.photos https://sample-videos.com https://www.learningcontainer.com https://*.firebasestorage.app; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://*.supabase.co https://firestore.googleapis.com https://identitytoolkit.googleapis.com https://*.amazonaws.com; frame-src 'self' https://accounts.google.com;"