-- Insert sample freelancer photographer data
-- This migration adds realistic sample data for testing the freelancer marketplace

-- Insert sample freelancers with photographer roles
INSERT INTO public.freelancers (
  id,
  name,
  role,
  location,
  rating,
  review_count,
  hourly_rate,
  avatar,
  specialties,
  is_available,
  email,
  phone,
  bio,
  experience_years,
  portfolio_url,
  website,
  linkedin,
  instagram,
  enlist_status,
  created_at,
  updated_at
) VALUES 
-- Professional Wedding Photographer
(
  gen_random_uuid(),
  'Sarah Johnson',
  'photographer',
  'Los Angeles, CA',
  4.9,
  127,
  '$150-200/hour',
  '/photosyncwork-logo.png',
  ARRAY['Wedding Photography', 'Portrait', 'Event Photography', 'Engagement'],
  true,
  'sarah.johnson@email.com',
  '+1 (555) 123-4567',
  'Professional wedding photographer with 8+ years of experience capturing life''s most precious moments. Specializing in elegant, timeless wedding photography that tells your unique love story.',
  8,
  'https://sarahjohnsonphotography.com',
  'https://sarahjohnsonphotography.com',
  'https://linkedin.com/in/sarahjohnsonphoto',
  '@sarahjohnsonphoto',
  'enlisted',
  now(),
  now()
),

-- Commercial Photography Specialist
(
  gen_random_uuid(),
  'Michael Chen',
  'photographer',
  'New York, NY',
  4.8,
  89,
  '$200-300/hour',
  '/photosyncwork-logo.png',
  ARRAY['Commercial Photography', 'Product Photography', 'Corporate', 'Fashion'],
  true,
  'michael.chen@email.com',
  '+1 (555) 234-5678',
  'Award-winning commercial photographer specializing in product and corporate photography. Known for creating compelling visual narratives that drive business results.',
  12,
  'https://michaelchenstudio.com',
  'https://michaelchenstudio.com',
  'https://linkedin.com/in/michaelchenphoto',
  '@michaelchenphoto',
  'enlisted',
  now(),
  now()
),

-- Portrait & Lifestyle Photographer
(
  gen_random_uuid(),
  'Emma Rodriguez',
  'photographer',
  'Miami, FL',
  4.7,
  156,
  '$100-150/hour',
  '/photosyncwork-logo.png',
  ARRAY['Portrait Photography', 'Lifestyle', 'Family', 'Maternity'],
  true,
  'emma.rodriguez@email.com',
  '+1 (555) 345-6789',
  'Passionate portrait photographer capturing authentic moments and genuine emotions. Specializing in family, maternity, and lifestyle photography with a warm, natural style.',
  6,
  'https://emmarodriguezphoto.com',
  'https://emmarodriguezphoto.com',
  'https://linkedin.com/in/emmarodriguezphoto',
  '@emmarodriguezphoto',
  'enlisted',
  now(),
  now()
),

-- Event & Concert Photographer
(
  gen_random_uuid(),
  'David Thompson',
  'photographer',
  'Austin, TX',
  4.6,
  73,
  '$120-180/hour',
  '/photosyncwork-logo.png',
  ARRAY['Event Photography', 'Concert Photography', 'Music Events', 'Corporate Events'],
  true,
  'david.thompson@email.com',
  '+1 (555) 456-7890',
  'Dynamic event photographer specializing in music and corporate events. Capturing the energy and excitement of live performances and special occasions.',
  5,
  'https://davidthompsonevents.com',
  'https://davidthompsonevents.com',
  'https://linkedin.com/in/davidthompsonevents',
  '@davidthompsonevents',
  'enlisted',
  now(),
  now()
),

-- Real Estate Photography Expert
(
  gen_random_uuid(),
  'Lisa Park',
  'photographer',
  'Seattle, WA',
  4.9,
  94,
  '$80-120/hour',
  '/photosyncwork-logo.png',
  ARRAY['Real Estate Photography', 'Architecture', 'Interior Design', 'Property'],
  true,
  'lisa.park@email.com',
  '+1 (555) 567-8901',
  'Professional real estate photographer helping agents showcase properties at their best. Specializing in architectural photography and virtual tours.',
  7,
  'https://lisaparkrealestate.com',
  'https://lisaparkrealestate.com',
  'https://linkedin.com/in/lisaparkrealestate',
  '@lisaparkrealestate',
  'enlisted',
  now(),
  now()
),

-- Fashion & Editorial Photographer
(
  gen_random_uuid(),
  'Alex Rivera',
  'photographer',
  'San Francisco, CA',
  4.8,
  112,
  '$180-250/hour',
  '/photosyncwork-logo.png',
  ARRAY['Fashion Photography', 'Editorial', 'Beauty', 'Lifestyle'],
  true,
  'alex.rivera@email.com',
  '+1 (555) 678-9012',
  'Creative fashion and editorial photographer with a bold, contemporary style. Working with brands, models, and publications to create striking visual content.',
  9,
  'https://alexriverafashion.com',
  'https://alexriverafashion.com',
  'https://linkedin.com/in/alexriverafashion',
  '@alexriverafashion',
  'enlisted',
  now(),
  now()
),

-- Food & Restaurant Photographer
(
  gen_random_uuid(),
  'Maria Santos',
  'photographer',
  'Portland, OR',
  4.7,
  68,
  '$90-130/hour',
  '/photosyncwork-logo.png',
  ARRAY['Food Photography', 'Restaurant', 'Culinary', 'Product'],
  true,
  'maria.santos@email.com',
  '+1 (555) 789-0123',
  'Specialized food photographer working with restaurants, chefs, and food brands. Creating mouth-watering images that showcase culinary artistry.',
  4,
  'https://mariasantosfood.com',
  'https://mariasantosfood.com',
  'https://linkedin.com/in/mariasantosfood',
  '@mariasantosfood',
  'enlisted',
  now(),
  now()
),

-- Sports & Action Photographer
(
  gen_random_uuid(),
  'James Wilson',
  'photographer',
  'Denver, CO',
  4.6,
  85,
  '$140-200/hour',
  '/photosyncwork-logo.png',
  ARRAY['Sports Photography', 'Action Photography', 'Athletics', 'Outdoor Sports'],
  true,
  'james.wilson@email.com',
  '+1 (555) 890-1234',
  'Dynamic sports photographer capturing the intensity and emotion of athletic competition. Specializing in outdoor sports and action photography.',
  6,
  'https://jameswilsonsports.com',
  'https://jameswilsonsports.com',
  'https://linkedin.com/in/jameswilsonsports',
  '@jameswilsonsports',
  'enlisted',
  now(),
  now()
),

-- Travel & Adventure Photographer
(
  gen_random_uuid(),
  'Sophie Kim',
  'photographer',
  'San Diego, CA',
  4.8,
  143,
  '$110-160/hour',
  '/photosyncwork-logo.png',
  ARRAY['Travel Photography', 'Adventure', 'Landscape', 'Documentary'],
  true,
  'sophie.kim@email.com',
  '+1 (555) 901-2345',
  'Adventure travel photographer documenting the world''s most beautiful destinations. Creating compelling visual stories of cultures, landscapes, and experiences.',
  10,
  'https://sophiekimtravel.com',
  'https://sophiekimtravel.com',
  'https://linkedin.com/in/sophiekimtravel',
  '@sophiekimtravel',
  'enlisted',
  now(),
  now()
),

-- Pet & Animal Photographer
(
  gen_random_uuid(),
  'Robert Davis',
  'photographer',
  'Nashville, TN',
  4.9,
  76,
  '$95-140/hour',
  '/photosyncwork-logo.png',
  ARRAY['Pet Photography', 'Animal Photography', 'Wildlife', 'Portrait'],
  true,
  'robert.davis@email.com',
  '+1 (555) 012-3456',
  'Passionate pet and animal photographer capturing the unique personalities of our furry friends. Specializing in pet portraits and wildlife photography.',
  5,
  'https://robertdavispets.com',
  'https://robertdavispets.com',
  'https://linkedin.com/in/robertdavispets',
  '@robertdavispets',
  'enlisted',
  now(),
  now()
);

-- Insert some job postings to make the marketplace more realistic
INSERT INTO public.job_postings (
  id,
  title,
  company,
  location,
  type,
  budget,
  date,
  description,
  requirements,
  created_at,
  updated_at
) VALUES 
(
  gen_random_uuid(),
  'Wedding Photographer Needed',
  'Elegant Events Co.',
  'Los Angeles, CA',
  'Contract',
  '$2,000 - $3,500',
  'March 15, 2024',
  'We need an experienced wedding photographer for a luxury wedding in Beverly Hills. Must have portfolio of high-end weddings and excellent client communication skills.',
  ARRAY['5+ years wedding experience', 'Professional equipment', 'Portfolio required', 'References needed'],
  now(),
  now()
),

(
  gen_random_uuid(),
  'Product Photography Project',
  'TechStart Inc.',
  'San Francisco, CA',
  'Project',
  '$1,500 - $2,500',
  'February 28, 2024',
  'Looking for a photographer to shoot our new tech products for marketing materials. Need clean, professional product shots with studio lighting.',
  ARRAY['Product photography experience', 'Studio lighting skills', 'Post-processing knowledge', 'Portfolio required'],
  now(),
  now()
),

(
  gen_random_uuid(),
  'Real Estate Photography',
  'Premier Properties',
  'Seattle, WA',
  'Ongoing',
  '$100 - $150 per property',
  '2024-03-01',
  'We need a reliable photographer for our luxury real estate listings. Must be able to shoot interiors, exteriors, and create virtual tours.',
  ARRAY['Real estate photography', 'Virtual tour experience', 'Professional equipment', 'Flexible schedule'],
  now(),
  now()
),

(
  gen_random_uuid(),
  'Event Photography - Corporate Gala',
  'Global Marketing Solutions',
  'New York, NY',
  'One-time',
  '$800 - $1,200',
  'March 10, 2024',
  'Corporate gala event photography needed. Must capture candid moments, group photos, and keynote presentations. Professional attire required.',
  ARRAY['Event photography experience', 'Professional appearance', 'Fast turnaround', 'High-quality equipment'],
  now(),
  now()
),

(
  gen_random_uuid(),
  'Fashion Photography Campaign',
  'Style Forward Brand',
  'Miami, FL',
  'Campaign',
  '$3,000 - $5,000',
  'April 1, 2024',
  'Creative fashion photographer needed for spring campaign. Looking for someone with bold, contemporary style and experience with fashion brands.',
  ARRAY['Fashion photography portfolio', 'Creative vision', 'Model direction skills', 'Post-production expertise'],
  now(),
  now()
);

-- Add some freelancers with different enlist statuses for testing
INSERT INTO public.freelancers (
  id,
  name,
  role,
  location,
  rating,
  review_count,
  hourly_rate,
  avatar,
  specialties,
  is_available,
  email,
  phone,
  bio,
  experience_years,
  portfolio_url,
  website,
  linkedin,
  instagram,
  enlist_status,
  created_at,
  updated_at
) VALUES 
-- Delisted photographer (for testing enlist/delist functionality)
(
  gen_random_uuid(),
  'Test Photographer',
  'photographer',
  'Test City, TS',
  4.5,
  25,
  '$75-100/hour',
  '/photosyncwork-logo.png',
  ARRAY['Test Photography', 'Sample Work'],
  true,
  'test.photographer@email.com',
  '+1 (555) 999-9999',
  'This is a test photographer profile for testing purposes.',
  2,
  'https://testphotographer.com',
  'https://testphotographer.com',
  'https://linkedin.com/in/testphotographer',
  '@testphotographer',
  'delisted',
  now(),
  now()
);

-- Add comment explaining the sample data
COMMENT ON TABLE public.freelancers IS 'Contains sample freelancer data for testing the marketplace functionality';
COMMENT ON TABLE public.job_postings IS 'Contains sample job postings for testing the hiring functionality';
