// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qozhzuekdwxvnrqxyxsr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvemh6dWVrZHd4dm5ycXh5eHNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2NTU0NTUsImV4cCI6MjA1NjIzMTQ1NX0.EuLEmNvi2vC3qDbKzBXcuMZ8QyyaThg5UPgGBfD0uj4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);